"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

"files": [
  {
    "source": "languages/en/en_*.json",
    "dest": "Skull and Bones Data/%original_file_name%",
    "translation": "languages/%two_letters_code%/%two_letters_code%_%original_file_name%"
  },
]